-- Accounts

CREATE TABLE GL00100 (
	ACTINDX int primary key,
	ACTNUMBR_1 char(9) NOT NULL default '10',
	ACTNUMBR_2 char(9) NOT NULL default '100',
	ACTNUMBR_3 char(9) NOT NULL default '1000',
	ACTNUMBR_4 char(9) NOT NULL default '1000',
	ACTNUMBR_5 char(9) NOT NULL default '',
	ACTNUMBR_6 char(9) NOT NULL default '',
	ACTALIAS char(21) NOT NULL default '',
	MNACSGMT char(67) NOT NULL default '',
	ACCTTYPE smallint NOT NULL default 1,
	ACTDESCR char(51) NOT NULL default 'TEST ACCOUNT',
	PSTNGTYP smallint NOT NULL default 0,
	ACCATNUM smallint NOT NULL default 0,
	ACTIVE   tinyint  NOT NULL default 1,
	TPCLBLNC smallint NOT NULL default 0,
	DECPLACS smallint NOT NULL default 0,
	FXDORVAR smallint NOT NULL default 0,
	BALFRCLC smallint NOT NULL default 0,
	DSPLKUPS binary(4) NOT NULL default 0,
	CNVRMTHD smallint NOT NULL default 0,
	HSTRCLRT numeric(19, 7) NOT NULL default 0,
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	CREATDDT datetime NOT NULL default getdate(),
	MODIFDT  datetime NOT NULL default getdate(),
	USERDEF1 char(21) NOT NULL default '',
	USERDEF2 char(21) NOT NULL default '',
	PostSlsIn smallint NOT NULL default 0,
	PostIvIn  smallint NOT NULL default 0,
	PostPurchIn smallint NOT NULL default 0,
	PostPRIn smallint NOT NULL default 0,
	ADJINFL  tinyint NOT NULL default 0,
	INFLAREV int NOT NULL default 0,
	INFLAEQU int NOT NULL default 0,
	ACCTENTR tinyint NOT NULL default 0,
	USRDEFS1 char(31) NOT NULL default '',
	USRDEFS2 char(31) NOT NULL default '',
	Clear_Balance tinyint NOT NULL default 0,
	Workflow_Status smallint NOT NULL default 0,
	DEX_ROW_TS datetime NOT NULL default getdate(),
	DEX_ROW_ID int IDENTITY NOT NULL)
GO

insert into GL00100 (ACTINDX) values (1)
GO

-- Customers

CREATE TABLE RM00101 (
	CUSTNMBR char(15) primary key,
	CUSTNAME char(65) NOT NULL default 'TEST CUSTOMER',
	CUSTCLAS char(15) NOT NULL default 'CLASS',
	CPRCSTNM char(15) NOT NULL default 'TEST',
	CNTCPRSN char(61) NOT NULL default 'JANE TESTER',
	STMTNAME char(65) NOT NULL default 'TEST CUSTOMER',
	SHRTNAME char(15) NOT NULL default 'TEST',
	ADRSCODE char(15) NOT NULL default '',
	UPSZONE  char(3) NOT NULL default '',
	SHIPMTHD char(15) NOT NULL default '',
	TAXSCHID char(15) NOT NULL default '',
	ADDRESS1 char(61) NOT NULL default '123 TEST STREET',
	ADDRESS2 char(61) NOT NULL default '',
	ADDRESS3 char(61) NOT NULL default '',
	COUNTRY  char(61) NOT NULL default 'CANADA',
	CITY  char(35) NOT NULL default 'SAULT STE. MARIE',
	STATE char(29) NOT NULL default 'ONTARIO',
	ZIP char(11) NOT NULL default 'P6A 1A1',
	PHONE1 char(21) NOT NULL default '5555555555',
	PHONE2 char(21) NOT NULL default '',
	PHONE3 char(21) NOT NULL default '',
	FAX char(21) NOT NULL default '',
	PRBTADCD char(15) NOT NULL default '',
	PRSTADCD char(15) NOT NULL default '',
	STADDRCD char(15) NOT NULL default '',
	SLPRSNID char(15) NOT NULL default '',
	CHEKBKID char(15) NOT NULL default '',
	PYMTRMID char(21) NOT NULL default '',
	CRLMTTYP smallint NOT NULL default 0,
	CRLMTAMT numeric(19, 5) NOT NULL default 0,
	CRLMTPER smallint NOT NULL default 0,
	CRLMTPAM numeric(19, 5) NOT NULL default 0,
	CURNCYID char(15) NOT NULL default '',
	RATETPID char(15) NOT NULL default '',
	CUSTDISC smallint NOT NULL default 0,
	PRCLEVEL char(11) NOT NULL default '',
	MINPYTYP smallint NOT NULL default 0,
	MINPYDLR numeric(19, 5) NOT NULL default 0,
	MINPYPCT smallint NOT NULL default 0,
	FNCHATYP smallint NOT NULL default 0,
	FNCHPCNT smallint NOT NULL default 0,
	FINCHDLR numeric(19, 5) NOT NULL default 0,
	MXWOFTYP smallint NOT NULL default 0,
	MXWROFAM numeric(19, 5) NOT NULL default 0,
	COMMENT1 char(31) NOT NULL default 'TEST COMMENT',
	COMMENT2 char(31) NOT NULL default '',
	USERDEF1 char(21) NOT NULL default '',
	USERDEF2 char(21) NOT NULL default '',
	TAXEXMT1 char(25) NOT NULL default '',
	TAXEXMT2 char(25) NOT NULL default '',
	TXRGNNUM char(25) NOT NULL default '',
	BALNCTYP smallint NOT NULL default 0,
	STMTCYCL smallint NOT NULL default 0,
	BANKNAME char(31) NOT NULL default 'TEST BANK',
	BNKBRNCH char(21) NOT NULL default 'TEST BRANCH',
	SALSTERR char(15) NOT NULL default '',
	DEFCACTY smallint NOT NULL default 0,
	RMCSHACC int NOT NULL default 0,
	RMARACC  int NOT NULL default 0,
	RMSLSACC int NOT NULL default 0,
	RMIVACC  int NOT NULL default 0,
	RMCOSACC int NOT NULL default 0,
	RMTAKACC int NOT NULL default 0,
	RMAVACC  int NOT NULL default 0,
	RMFCGACC int NOT NULL default 0,
	RMWRACC  int NOT NULL default 0,
	RMSORACC int NOT NULL default 0,
	FRSTINDT datetime NOT NULL default getdate(),
	INACTIVE tinyint NOT NULL default 0,
	HOLD tinyint NOT NULL default 0,
	CRCARDID char(15) NOT NULL default '',
	CRCRDNUM char(21) NOT NULL default '',
	CCRDXPDT datetime NOT NULL default getdate(),
	KPDSTHST tinyint NOT NULL default 0,
	KPCALHST tinyint NOT NULL default 0,
	KPERHIST tinyint NOT NULL default 0,
	KPTRXHST tinyint NOT NULL default 0,
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	CREATDDT datetime NOT NULL default getdate(),
	MODIFDT  datetime NOT NULL default getdate(),
	Revalue_Customer tinyint  NOT NULL default 0,
	Post_Results_To  smallint NOT NULL default 0,
	FINCHID  char(15) NOT NULL default '',
	GOVCRPID char(31) NOT NULL default '',
	GOVINDID char(31) NOT NULL default '',
	DISGRPER smallint NOT NULL default 0,
	DUEGRPER smallint NOT NULL default 0,
	DOCFMTID char(15) NOT NULL default '',
	Send_Email_Statements tinyint NOT NULL default 0,
	USERLANG smallint NOT NULL default 0,
	GPSFOINTEGRATIONID char(31) NOT NULL default '',
	INTEGRATIONSOURCE smallint NOT NULL default 0,
	INTEGRATIONID char(31) NOT NULL default '',
	ORDERFULFILLDEFAULT smallint NOT NULL default 0,
	CUSTPRIORITY smallint NOT NULL default 0,
	CCode  char(7) NOT NULL default '',
	DECLID char(15) NOT NULL default '',
	RMOvrpymtWrtoffAcctIdx int NOT NULL default 0,
	SHIPCOMPLETE tinyint NOT NULL default 0,
	CBVAT tinyint NOT NULL default 0,
	INCLUDEINDP tinyint NOT NULL default 0,
	DEX_ROW_TS datetime NOT NULL default getdate(),
	DEX_ROW_ID int IDENTITY NOT NULL)
GO

insert into RM00101 (CUSTNMBR) values ('CUST001')

-- Invoices

CREATE TABLE IVC10100 (
	DOCTYPE smallint NOT NULL,
	INVCNMBR char(21) NOT NULL,
	BACHNUMB char(15) NOT NULL default 'BATCH001',
	BCHSOURC char(15) NOT NULL default '',
	PCKSLPNO char(21) NOT NULL default '',
	CUSTNMBR char(15) NOT NULL default 'CUST001',
	CUSTNAME char(65) NOT NULL default 'TEST CUSTOMER',
	CSTPONBR char(21) NOT NULL default '',
	POSTDATE datetime NOT NULL default getdate(),
	GLPOSTDT datetime NOT NULL default getdate(),
	DOCDATE datetime NOT NULL default getdate(),
	QUOTEDAT datetime NOT NULL default getdate(),
	ORDRDATE datetime NOT NULL default getdate(),
	DISCDATE datetime NOT NULL default getdate(),
	DUEDATE datetime NOT NULL default getdate(),
	HOLDNT tinyint NOT NULL default 0,
	SHIPMTHD char(15) NOT NULL default '',
	TAXEXMT1 char(25) NOT NULL default '',
	TAXEXMT2 char(25) NOT NULL default '',
	TAXSCHID char(15) NOT NULL default '',
	FRTSCHID char(15) NOT NULL default '',
	FRGTTXBL smallint NOT NULL default 0,
	FRTTXAMT numeric(19, 5) NOT NULL default 0,
	MSCSCHID char(15) NOT NULL default '',
	MISCTXBL smallint NOT NULL default 0,
	MSCTXAMT numeric(19, 5) NOT NULL default 0,
	SLPRSNID char(15) NOT NULL default '',
	SALSTERR char(15) NOT NULL default '',
	TXRGNNUM char(25) NOT NULL default '',
	PYMTRMID char(21) NOT NULL default '',
	PRCLEVEL char(11) NOT NULL default '',
	LOCNCODE char(11) NOT NULL default '',
	CURNCYID char(15) NOT NULL default '',
	COMMNTID char(15) NOT NULL default '',
	DOCAMNT numeric(19, 5) NOT NULL default 100,
	SUBTOTAL numeric(19, 5) NOT NULL default 100,
	FRTAMNT numeric(19, 5) NOT NULL default 0,
	MISCAMNT numeric(19, 5) NOT NULL default 0,
	TAXAMNT numeric(19, 5) NOT NULL default 0,
	TXBTXAMT numeric(19, 5) NOT NULL default 0,
	BCKTXAMT numeric(19, 5) NOT NULL default 0,
	BKTSLSAM numeric(19, 5) NOT NULL default 0,
	BKTFRTAM numeric(19, 5) NOT NULL default 0,
	BKTMSCAM numeric(19, 5) NOT NULL default 0,
	DISCFRGT numeric(19, 5) NOT NULL default 0,
	DISCMISC numeric(19, 5) NOT NULL default 0,
	TRDISPCT smallint NOT NULL default 0,
	TRDISAMT numeric(19, 5) NOT NULL default 0,
	ACCTAMNT numeric(19, 5) NOT NULL default 0,
	PYMTRCVD numeric(19, 5) NOT NULL default 100,
	CODAMNT numeric(19, 5) NOT NULL default 0,
	EXTDCOST numeric(19, 5) NOT NULL default 0,
	DISCRTND numeric(19, 5) NOT NULL default 0,
	DISAVTKN numeric(19, 5) NOT NULL default 0,
	DISTKNAM numeric(19, 5) NOT NULL default 0,
	DISAVAMT numeric(19, 5) NOT NULL default 0,
	DSCDLRAM numeric(19, 5) NOT NULL default 0,
	DSCPCTAM smallint NOT NULL default 0,
	MRKDNAMT numeric(19, 5) NOT NULL default 0,
	PRBTADCD char(15) NOT NULL default '',
	PRSTADCD char(15) NOT NULL default '',
	CNTCPRSN char(61) NOT NULL default 'JANE TESTER',
	ADDRESS1 char(61) NOT NULL default '123 TEST STREET',
	ADDRESS2 char(61) NOT NULL default '',
	ADDRESS3 char(61) NOT NULL default '',
	CITY char(35) NOT NULL default 'SAULT STE. MARIE',
	STATE char(29) NOT NULL default 'ONTARIO',
	ZIPCODE char(11) NOT NULL default 'P6A 1A1',
	CCode char(7) NOT NULL default '',
	COUNTRY char(61) NOT NULL default 'CANADA',
	PHNUMBR1 char(21) NOT NULL default '5555555555',
	PHNUMBR2 char(21) NOT NULL default '',
	PHONE3 char(21) NOT NULL default '',
	FAXNUMBR char(21) NOT NULL default '',
	COMAPPTO smallint NOT NULL default 0,
	COMDLRAM numeric(19, 5) NOT NULL default 0,
	NCOMAMNT numeric(19, 5) NOT NULL default 0,
	UPSZONE char(3) NOT NULL default '',
	LSTUSRED char(15) NOT NULL default '',
	LSTEDTDT datetime NOT NULL default getdate(),
	MODIFDT datetime NOT NULL default getdate(),
	CREATDDT datetime NOT NULL default getdate(),
	USER2ENT char(15) NOT NULL default '',
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	TIMESPRT smallint NOT NULL default 0,
	NOCARTNS smallint NOT NULL default 0,
	USERDEF1 char(21) NOT NULL default '',
	USERDEF2 char(21) NOT NULL default '',
	VOIDSTTS smallint NOT NULL default 0,
	TRXSORCE char(13) NOT NULL default '',
	PSTGSTUS smallint NOT NULL default 0,
	IVCHDER1 binary(4) NOT NULL default 0,
	IVCHDER2 binary(4) NOT NULL default 0,
	IVCLINEERR binary(4) NOT NULL default 0,
	LNITMSEQ int NOT NULL default 0,
	COMMENT_1 char(51) NOT NULL default 'TEST COMMENT',
	COMMENT_2 char(51) NOT NULL default '',
	COMMENT_3 char(51) NOT NULL default '',
	COMMENT_4 char(51) NOT NULL default '',
	ECTRX tinyint NOT NULL default 0,
	ShipToName char(65) NOT NULL default '',
	Tax_Date datetime NOT NULL default getdate(),
	APLYWITH tinyint NOT NULL default 0,
	WITHHAMT numeric(19, 5) NOT NULL default 0,
	BackoutTradeDisc numeric(19, 5) NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
	CMMTTEXT text NOT NULL default '',
 CONSTRAINT PKIVC10100 PRIMARY KEY NONCLUSTERED (INVCNMBR, DOCTYPE))
GO

CREATE TABLE IVC30101 (
	DOCTYPE smallint NOT NULL,
	INVCNMBR char(21) NOT NULL,
	BACHNUMB char(15) NOT NULL default 'BATCH001',
	BCHSOURC char(15) NOT NULL default '',
	PCKSLPNO char(21) NOT NULL default '',
	CUSTNMBR char(15) NOT NULL default 'CUST001',
	CUSTNAME char(65) NOT NULL default 'TEST CUSTOMER',
	CSTPONBR char(21) NOT NULL default '',
	POSTDATE datetime NOT NULL default getdate(),
	GLPOSTDT datetime NOT NULL default getdate(),
	DOCDATE datetime NOT NULL default getdate(),
	QUOTEDAT datetime NOT NULL default getdate(),
	ORDRDATE datetime NOT NULL default getdate(),
	DISCDATE datetime NOT NULL default getdate(),
	DUEDATE datetime NOT NULL default getdate(),
	HOLDNT tinyint NOT NULL default 0,
	SHIPMTHD char(15) NOT NULL default '',
	TAXEXMT1 char(25) NOT NULL default '',
	TAXEXMT2 char(25) NOT NULL default '',
	TAXSCHID char(15) NOT NULL default '',
	FRTSCHID char(15) NOT NULL default '',
	FRGTTXBL smallint NOT NULL default 0,
	FRTTXAMT numeric(19, 5) NOT NULL default 0,
	MSCSCHID char(15) NOT NULL default '',
	MISCTXBL smallint NOT NULL default 0,
	MSCTXAMT numeric(19, 5) NOT NULL default 0,
	MRKDNAMT numeric(19, 5) NOT NULL default 0,
	SLPRSNID char(15) NOT NULL default '',
	SALSTERR char(15) NOT NULL default '',
	TXRGNNUM char(25) NOT NULL default '',
	PYMTRMID char(21) NOT NULL default '',
	PRCLEVEL char(11) NOT NULL default '',
	LOCNCODE char(11) NOT NULL default '',
	CURNCYID char(15) NOT NULL default '',
	COMMNTID char(15) NOT NULL default '',
	DOCAMNT numeric(19, 5) NOT NULL default 100,
	SUBTOTAL numeric(19, 5) NOT NULL default 100,
	FRTAMNT numeric(19, 5) NOT NULL default 0,
	MISCAMNT numeric(19, 5) NOT NULL default 0,
	TAXAMNT numeric(19, 5) NOT NULL default 0,
	TXBTXAMT numeric(19, 5) NOT NULL default 0,
	TRDISAMT numeric(19, 5) NOT NULL default 0,
	ACCTAMNT numeric(19, 5) NOT NULL default 0,
	PYMTRCVD numeric(19, 5) NOT NULL default 100,
	CODAMNT numeric(19, 5) NOT NULL default 0,
	EXTDCOST numeric(19, 5) NOT NULL default 0,
	DISAVTKN numeric(19, 5) NOT NULL default 0,
	DISCRTND numeric(19, 5) NOT NULL default 0,
	DISTKNAM numeric(19, 5) NOT NULL default 0,
	DISAVAMT numeric(19, 5) NOT NULL default 0,
	DSCDLRAM numeric(19, 5) NOT NULL default 0,
	DSCPCTAM smallint NOT NULL default 0,
	PRBTADCD char(15) NOT NULL default '',
	PRSTADCD char(15) NOT NULL default '',
	CNTCPRSN char(61) NOT NULL default 'JANE TESTER',
	ADDRESS1 char(61) NOT NULL default '123 TEST STREET',
	ADDRESS2 char(61) NOT NULL default '',
	ADDRESS3 char(61) NOT NULL default '',
	CITY char(35) NOT NULL default 'SAULT STE. MARIE',
	STATE char(29) NOT NULL default 'ONTARIO',
	ZIPCODE char(11) NOT NULL default 'P6A 1A1',
	CCode char(7) NOT NULL default '',
	COUNTRY char(61) NOT NULL default 'CANADA',
	PHNUMBR1 char(21) NOT NULL default '5555555555',
	PHNUMBR2 char(21) NOT NULL default '',
	PHONE3 char(21) NOT NULL default '',
	FAXNUMBR char(21) NOT NULL default '',
	COMAPPTO smallint NOT NULL default 0,
	COMDLRAM numeric(19, 5) NOT NULL default 0,
	NCOMAMNT numeric(19, 5) NOT NULL default 0,
	UPSZONE char(3) NOT NULL default '',
	LSTUSRED char(15) NOT NULL default '',
	LSTEDTDT datetime NOT NULL default getdate(),
	MODIFDT datetime NOT NULL default getdate(),
	CREATDDT datetime NOT NULL default getdate(),
	USER2ENT char(15) NOT NULL default '',
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	TIMESPRT smallint NOT NULL default 0,
	NOCARTNS smallint NOT NULL default 0,
	USERDEF1 char(21) NOT NULL default '',
	USERDEF2 char(21) NOT NULL default '',
	VOIDSTTS smallint NOT NULL default 0,
	TRXSORCE char(13) NOT NULL default '',
	LNITMSEQ int NOT NULL default 0,
	COMMENT_1 char(51) NOT NULL default 'TEST COMMENT',
	COMMENT_2 char(51) NOT NULL default '',
	COMMENT_3 char(51) NOT NULL default '',
	COMMENT_4 char(51) NOT NULL default '',
	ECTRX tinyint NOT NULL default 0,
	ShipToName char(65) NOT NULL default '',
	Tax_Date datetime NOT NULL default getdate(),
	APLYWITH tinyint NOT NULL default 0,
	WITHHAMT numeric(19, 5) NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
	CMMTTEXT text NOT NULL default '',
 CONSTRAINT PKIVC30101 PRIMARY KEY NONCLUSTERED (INVCNMBR, DOCTYPE))
GO

insert into IVC30101 (DOCTYPE, INVCNMBR) values (1, 'IVC000001')

-- Invoice Line Items

CREATE TABLE IVC10101 (
	DOCTYPE smallint NOT NULL,
	INVCNMBR char(21) NOT NULL,
	LNITMSEQ int NOT NULL,
	CMPNTSEQ int NOT NULL,
	ITEMNMBR char(31) NOT NULL default '01-0001-00001',
	DECPLCUR smallint NOT NULL default 0,
	DECPLQTY smallint NOT NULL default 0,
	INVINDX int NOT NULL default 0,
	CSLSINDX int NOT NULL default 0,
	SLSINDX int NOT NULL default 0,
	MKDNINDX int NOT NULL default 0,
	RTNSINDX int NOT NULL default 0,
	INUSINDX int NOT NULL default 0,
	INSRINDX int NOT NULL default 0,
	DMGDINDX int NOT NULL default 0,
	ITMTSHID char(15) NOT NULL default '',
	IVITMTXB smallint NOT NULL default 0,
	NONINVEN smallint NOT NULL default 0,
	QUANTITY numeric(19, 5) NOT NULL default 10,
	QTYINSVC numeric(19, 5) NOT NULL default 0,
	QTYINUSE numeric(19, 5) NOT NULL default 0,
	QTYDMGED numeric(19, 5) NOT NULL default 0,
	QTYRTRND numeric(19, 5) NOT NULL default 0,
	QTYONHND numeric(19, 5) NOT NULL default 0,
	EXTQTYSEL numeric(19, 5) NOT NULL default 0,
	UOFM char(9) NOT NULL default 'EACH',
	QTYBSUOM numeric(19, 5) NOT NULL default 0,
	UNITCOST numeric(19, 5) NOT NULL default 10,
	EXTDCOST numeric(19, 5) NOT NULL default 0,
	DISCSALE numeric(19, 5) NOT NULL default 0,
	TRDISAMT numeric(19, 5) NOT NULL default 0,
	ATYALLOC numeric(19, 5) NOT NULL default 0,
	LOCNCODE char(11) NOT NULL default '',
	MRKDNTYP smallint NOT NULL default 0,
	MRKDNAMT numeric(19, 5) NOT NULL default 0,
	MRKDNPCT smallint NOT NULL default 0,
	PRCLEVEL char(11) NOT NULL default '',
	XTNDPRCE numeric(19, 5) NOT NULL default 0,
	UNITPRCE numeric(19, 5) NOT NULL default 10,
	TAXAMNT numeric(19, 5) NOT NULL default 0,
	BKTSLSAM numeric(19, 5) NOT NULL default 0,
	TXBTXAMT numeric(19, 5) NOT NULL default 0,
	BSIVCTTL tinyint NOT NULL default 0,
	SLPRSNID char(15) NOT NULL default '',
	SALSTERR char(15) NOT NULL default '',
	DSCRIPTN char(31) NOT NULL default 'TEST ITEM'
	ITEMDESC char(101) NOT NULL default 'TEST ITEM',
	EXPTSHIP datetime NOT NULL default getdate(),
	ACTLSHIP datetime NOT NULL default getdate(),
	ReqShipDate datetime NOT NULL default getdate(),
	COMDLRAM numeric(19, 5) NOT NULL default 0,
	CMPSERNM tinyint NOT NULL default 0,
	COMMNTID char(15) NOT NULL default '',
	BRKFLD1 smallint NOT NULL default 0,
	BRKFLD2 smallint NOT NULL default 0,
	BRKFLD3 smallint NOT NULL default 0,
	TRXSORCE char(13) NOT NULL default '',
	IVCLINEERR binary(4) NOT NULL default 0,
	BackoutTradeDisc numeric(19, 5) NOT NULL default 0,
	PRSTADCD char(15) NOT NULL default '',
	SHIPMTHD char(15) NOT NULL default '',
	ISLINEINTRA tinyint NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
 CONSTRAINT PKIVC10101 PRIMARY KEY NONCLUSTERED (INVCNMBR, DOCTYPE, CMPNTSEQ, LNITMSEQ))
GO

CREATE TABLE IVC30102 (
	DOCTYPE smallint NOT NULL,
	INVCNMBR char(21) NOT NULL,
	LNITMSEQ int NOT NULL,
	CMPNTSEQ int NOT NULL,
	NONINVEN smallint NOT NULL default 1,
	ITEMNMBR char(31) NOT NULL default '01-0001-00001',
	DECPLCUR smallint NOT NULL default 0,
	DECPLQTY smallint NOT NULL default 0,
	ITMTSHID char(15) NOT NULL default '',
	IVITMTXB smallint NOT NULL default 0,
	QUANTITY numeric(19, 5) NOT NULL default 10,
	QTYINSVC numeric(19, 5) NOT NULL default 0,
	QTYINUSE numeric(19, 5) NOT NULL default 0,
	QTYDMGED numeric(19, 5) NOT NULL default 0,
	QTYRTRND numeric(19, 5) NOT NULL default 0,
	QTYONHND numeric(19, 5) NOT NULL default 0,
	EXTQTYSEL numeric(19, 5) NOT NULL default 0,
	UOFM char(9) NOT NULL default 'EACH',
	QTYBSUOM numeric(19, 5) NOT NULL default 0,
	UNITCOST numeric(19, 5) NOT NULL default 10,
	EXTDCOST numeric(19, 5) NOT NULL default 0,
	ATYALLOC numeric(19, 5) NOT NULL default 0,
	LOCNCODE char(11) NOT NULL default '',
	MRKDNTYP smallint NOT NULL default 0,
	MRKDNAMT numeric(19, 5) NOT NULL default 0,
	MRKDNPCT smallint NOT NULL default 0,
	PRCLEVEL char(11) NOT NULL default '',
	XTNDPRCE numeric(19, 5) NOT NULL default 0,
	UNITPRCE numeric(19, 5) NOT NULL default 10,
	TAXAMNT numeric(19, 5) NOT NULL default 0,
	BKTSLSAM numeric(19, 5) NOT NULL default 0,
	TXBTXAMT numeric(19, 5) NOT NULL default 0,
	SLPRSNID char(15) NOT NULL default '',
	SALSTERR char(15) NOT NULL default '',
	DSCRIPTN char(31) NOT NULL default 'TEST ITEM',
	ITEMDESC char(101) NOT NULL default 'TEST ITEM',
	EXPTSHIP datetime NOT NULL default getdate(),
	ACTLSHIP datetime NOT NULL default getdate(),
	ReqShipDate datetime NOT NULL default getdate(),
	COMDLRAM numeric(19, 5) NOT NULL default 0,
	CMPSERNM tinyint NOT NULL default 0,
	COMMNTID char(15) NOT NULL default '',
	BRKFLD1 smallint NOT NULL default 0,
	BRKFLD2 smallint NOT NULL default 0,
	BRKFLD3 smallint NOT NULL default 0,
	TRXSORCE char(13) NOT NULL default '',
	PRSTADCD char(15) NOT NULL default '',
	SHIPMTHD char(15) NOT NULL default '',
	ISLINEINTRA tinyint NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
 CONSTRAINT PKIVC30102 PRIMARY KEY NONCLUSTERED 
(
	INVCNMBR ASC,
	DOCTYPE ASC,
	CMPNTSEQ ASC,
	LNITMSEQ ASC
))
GO

insert into IVC30102 (DOCTYPE, INVCNMBR, CMPNTSEQ, LNITMSEQ)
values (1, 'IVC000001', 1, 1)

-- Invoice Document Types

CREATE TABLE IVC40101 (
	DOCTYPE smallint primary key,
	DOCTYABR char(3) NOT NULL,
	DOCTYNAM char(21) NOT NULL,
	INVCNMBR char(21) NOT NULL default '',
	SETUPKEY smallint NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL)
GO

insert into IVC40101 (DOCTYPE, DOCTYABR, DOCTYNAM) values (1, 'IVC', 'Invoice')
GO

-- Items

CREATE TABLE IV00101 (
	ITEMNMBR char(31) primary key,
	ITEMDESC char(101) NOT NULL default 'TEST ITEM',
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	ITMSHNAM char(15) NOT NULL default 'ITEM',
	ITEMTYPE smallint NOT NULL default 0,
	ITMGEDSC char(11) NOT NULL default '',
	STNDCOST numeric(19, 5) NOT NULL default 10,
	CURRCOST numeric(19, 5) NOT NULL default 12,
	ITEMSHWT int NOT NULL  default 0,
	DECPLQTY smallint NOT NULL default 0,
	DECPLCUR smallint NOT NULL default 0,
	ITMTSHID char(15) NOT NULL default '',
	TAXOPTNS smallint NOT NULL default 0,
	IVIVINDX int NOT NULL default 0,
	IVIVOFIX int NOT NULL default 0,
	IVCOGSIX int NOT NULL default 0,
	IVSLSIDX int NOT NULL default 0,
	IVSLDSIX int NOT NULL default 0,
	IVSLRNIX int NOT NULL default 0,
	IVINUSIX int NOT NULL default 0,
	IVINSVIX int NOT NULL default 0,
	IVDMGIDX int NOT NULL default 0,
	IVVARIDX int NOT NULL default 0,
	DPSHPIDX int NOT NULL default 0,
	PURPVIDX int NOT NULL default 0,
	UPPVIDX int NOT NULL default 0,
	IVRETIDX int NOT NULL default 0,
	ASMVRIDX int NOT NULL default 0,
	ITMCLSCD char(11) NOT NULL default '',
	ITMTRKOP smallint NOT NULL default 0,
	LOTTYPE char(11) NOT NULL default '',
	KPERHIST tinyint NOT NULL default 0,
	KPTRXHST tinyint NOT NULL default 0,
	KPCALHST tinyint NOT NULL default 0,
	KPDSTHST tinyint NOT NULL default 0,
	ALWBKORD tinyint NOT NULL default 0,
	VCTNMTHD smallint NOT NULL default 0,
	UOMSCHDL char(11) NOT NULL default '',
	ALTITEM1 char(31) NOT NULL default '',
	ALTITEM2 char(31) NOT NULL default '',
	USCATVLS_1 char(11) NOT NULL default '',
	USCATVLS_2 char(11) NOT NULL default '',
	USCATVLS_3 char(11) NOT NULL default '',
	USCATVLS_4 char(11) NOT NULL default '',
	USCATVLS_5 char(11) NOT NULL default '',
	USCATVLS_6 char(11) NOT NULL default '',
	MSTRCDTY smallint NOT NULL default 0,
	MODIFDT datetime NOT NULL default getdate(),
	CREATDDT datetime NOT NULL default getdate(),
	WRNTYDYS smallint NOT NULL default 0,
	PRCLEVEL char(11) NOT NULL default '',
	LOCNCODE char(11) NOT NULL default '',
	PINFLIDX int NOT NULL default 0,
	PURMCIDX int NOT NULL default 0,
	IVINFIDX int NOT NULL default 0,
	INVMCIDX int NOT NULL default 0,
	CGSINFLX int NOT NULL default 0,
	CGSMCIDX int NOT NULL default 0,
	ITEMCODE char(15) NOT NULL default '',
	TCC char(31) NOT NULL default '',
	PriceGroup char(11) NOT NULL default '',
	PRICMTHD smallint NOT NULL default 0,
	PRCHSUOM char(9) NOT NULL default '',
	SELNGUOM char(9) NOT NULL default '',
	KTACCTSR smallint NOT NULL default 0,
	LASTGENSN char(21) NOT NULL default '',
	ABCCODE smallint NOT NULL default 0,
	Revalue_Inventory tinyint NOT NULL default 0,
	Tolerance_Percentage int NOT NULL default 0,
	Purchase_Item_Tax_Schedu char(15) NOT NULL default '',
	Purchase_Tax_Options smallint NOT NULL default 0,
	ITMPLNNNGTYP smallint NOT NULL default 0,
	STTSTCLVLPRCNTG smallint NOT NULL default 0,
	CNTRYORGN char(7) NOT NULL default '',
	INACTIVE tinyint NOT NULL default 0,
	MINSHELF1 smallint NOT NULL default 0,
	MINSHELF2 smallint NOT NULL default 0,
	INCLUDEINDP tinyint NOT NULL default 0,
	LOTEXPWARN tinyint NOT NULL default 0,
	LOTEXPWARNDAYS smallint NOT NULL default 0,
	LASTGENLOT char(21) NOT NULL default '',
	Lot_Split_Quantity numeric(19, 5) NOT NULL default 0,
	UseQtyOverageTolerance tinyint NOT NULL default 0,
	UseQtyShortageTolerance tinyint NOT NULL default 0,
	QtyOverTolerancePercent int NOT NULL default 0,
	QtyShortTolerancePercent int NOT NULL default 0,
	IVSCRVIX int NOT NULL default 0,
	USERID char(15) NOT NULL default '',
	DEX_ROW_TS datetime NOT NULL default getdate(),
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL)
GO

insert into IV00101 (ITEMNMBR) values ('01-0001-00001')

-- Item Quantities

CREATE TABLE IV00102 (
	ITEMNMBR char(31) NOT NULL,
	LOCNCODE char(11) NOT NULL default '',
	BINNMBR char(21) NOT NULL default '',
	RCRDTYPE smallint NOT NULL default 0,
	PRIMVNDR char(15) NOT NULL default 'VEND001',
	ITMFRFLG tinyint NOT NULL default 0,
	BGNGQTY numeric(19, 5) NOT NULL default 1,
	LSORDQTY numeric(19, 5) NOT NULL default 5,
	LRCPTQTY numeric(19, 5) NOT NULL default 0,
	LSTORDDT datetime NOT NULL default getdate(),
	LSORDVND char(15) NOT NULL default 'VEND001',
	LSRCPTDT datetime NOT NULL default getdate(),
	QTYRQSTN numeric(19, 5) NOT NULL default 0,
	QTYONORD numeric(19, 5) NOT NULL default 0,
	QTYBKORD numeric(19, 5) NOT NULL default 3,
	QTY_Drop_Shipped numeric(19, 5) NOT NULL default 0,
	QTYINUSE numeric(19, 5) NOT NULL default 2,
	QTYINSVC numeric(19, 5) NOT NULL default 0,
	QTYRTRND numeric(19, 5) NOT NULL default 0,
	QTYDMGED numeric(19, 5) NOT NULL default 0,
	QTYONHND numeric(19, 5) NOT NULL default 0,
	ATYALLOC numeric(19, 5) NOT NULL default 0,
	QTYCOMTD numeric(19, 5) NOT NULL default 0,
	QTYSOLD numeric(19, 5) NOT NULL default 0,
	NXTCNTDT datetime NOT NULL default getdate(),
	NXTCNTTM datetime NOT NULL default getdate(),
	LSTCNTDT datetime NOT NULL default getdate(),
	LSTCNTTM datetime NOT NULL default getdate(),
	STCKCNTINTRVL smallint NOT NULL default 0,
	Landed_Cost_Group_ID char(15) NOT NULL default '',
	BUYERID char(15) NOT NULL default '',
	PLANNERID char(15) NOT NULL default '',
	ORDERPOLICY smallint NOT NULL default 0,
	FXDORDRQTY numeric(19, 5) NOT NULL default 0,
	ORDRPNTQTY numeric(19, 5) NOT NULL default 0,
	NMBROFDYS smallint NOT NULL default 0,
	MNMMORDRQTY numeric(19, 5) NOT NULL default 0,
	MXMMORDRQTY numeric(19, 5) NOT NULL default 0,
	ORDERMULTIPLE numeric(19, 5) NOT NULL default 0,
	REPLENISHMENTMETHOD smallint NOT NULL default 0,
	SHRINKAGEFACTOR numeric(19, 5) NOT NULL default 0,
	PRCHSNGLDTM numeric(19, 5) NOT NULL default 0,
	MNFCTRNGFXDLDTM numeric(19, 5) NOT NULL default 0,
	MNFCTRNGVRBLLDTM numeric(19, 5) NOT NULL default 0,
	STAGINGLDTME numeric(19, 5) NOT NULL default 0,
	PLNNNGTMFNCDYS smallint NOT NULL default 0,
	DMNDTMFNCPRDS smallint NOT NULL default 0,
	INCLDDINPLNNNG tinyint NOT NULL default 0,
	CALCULATEATP tinyint NOT NULL default 0,
	AUTOCHKATP tinyint NOT NULL default 0,
	PLNFNLPAB tinyint NOT NULL default 0,
	FRCSTCNSMPTNPRD smallint NOT NULL default 0,
	ORDRUPTOLVL numeric(19, 5) NOT NULL default 0,
	SFTYSTCKQTY numeric(19, 5) NOT NULL default 0,
	REORDERVARIANCE numeric(19, 5) NOT NULL default 0,
	PORECEIPTBIN char(15) NOT NULL default '',
	PORETRNBIN char(15) NOT NULL default '',
	SOFULFILLMENTBIN char(15) NOT NULL default '',
	SORETURNBIN char(15) NOT NULL default '',
	BOMRCPTBIN char(15) NOT NULL default '',
	MATERIALISSUEBIN char(15) NOT NULL default '',
	MORECEIPTBIN char(15) NOT NULL default '',
	REPAIRISSUESBIN char(15) NOT NULL default '',
	ReplenishmentLevel smallint NOT NULL default 0,
	POPOrderMethod smallint NOT NULL default 0,
	MasterLocationCode char(11) NOT NULL default '',
	POPVendorSelection smallint NOT NULL default 0,
	POPPricingSelection smallint NOT NULL default 0,
	PurchasePrice numeric(19, 5) NOT NULL default 10,
	IncludeAllocations tinyint NOT NULL default 0,
	IncludeBackorders tinyint NOT NULL default 0,
	IncludeRequisitions tinyint NOT NULL default 0,
	PICKTICKETITEMOPT smallint NOT NULL default 0,
	INCLDMRPMOVEIN tinyint NOT NULL default 0,
	INCLDMRPMOVEOUT tinyint NOT NULL default 0,
	INCLDMRPCANCEL tinyint NOT NULL default 0,
	Move_Out_Fence smallint NOT NULL default 0,
	INACTIVE tinyint NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
 CONSTRAINT PKIV00102 PRIMARY KEY NONCLUSTERED 
(
	ITEMNMBR ASC,
	RCRDTYPE ASC,
	LOCNCODE ASC
))
GO

insert into IV00102 (ITEMNMBR) values ('01-0001-00001')
GO

-- Vendors

CREATE TABLE PM00200 (
	VENDORID char(15) primary key,
	VENDNAME char(65) NOT NULL default 'TEST VENDOR',
	VNDCHKNM char(65) NOT NULL default 'TEST VENDOR',
	VENDSHNM char(15) NOT NULL default 'TEST',
	VADDCDPR char(15) NOT NULL default '',
	VADCDPAD char(15) NOT NULL default '',
	VADCDSFR char(15) NOT NULL default '',
	VADCDTRO char(15) NOT NULL default '',
	VNDCLSID char(11) NOT NULL default '',
	VNDCNTCT char(61) NOT NULL default '',
	ADDRESS1 char(61) NOT NULL default '123 TEST STREET',
	ADDRESS2 char(61) NOT NULL default '',
	ADDRESS3 char(61) NOT NULL default '',
	CITY char(35) NOT NULL default 'SAULT STE. MARIE',
	STATE char(29) NOT NULL default 'ONTARIO',
	ZIPCODE char(11) NOT NULL default 'P6A 1A1',
	COUNTRY char(61) NOT NULL default 'CANADA',
	PHNUMBR1 char(21) NOT NULL default '5555555555',
	PHNUMBR2 char(21) NOT NULL default '',
	PHONE3 char(21) NOT NULL default '',
	FAXNUMBR char(21) NOT NULL default '',
	UPSZONE char(3) NOT NULL default '',
	SHIPMTHD char(15) NOT NULL default '',
	TAXSCHID char(15) NOT NULL default '',
	ACNMVNDR char(21) NOT NULL default '',
	TXIDNMBR char(11) NOT NULL default '',
	VENDSTTS smallint NOT NULL default 0,
	CURNCYID char(15) NOT NULL default '',
	TXRGNNUM char(25) NOT NULL default '',
	PARVENID char(15) NOT NULL default '',
	TRDDISCT smallint NOT NULL default 0,
	TEN99TYPE smallint NOT NULL default 0,
	TEN99BOXNUMBER smallint NOT NULL default 0,
	MINORDER numeric(19, 5) NOT NULL default 5,
	PYMTRMID char(21) NOT NULL default '',
	MINPYTYP smallint NOT NULL default 0,
	MINPYPCT smallint NOT NULL default 0,
	MINPYDLR numeric(19, 5) NOT NULL default 0,
	MXIAFVND smallint NOT NULL default 0,
	MAXINDLR numeric(19, 5) NOT NULL default 0,
	COMMENT1 char(31) NOT NULL default 'TEST COMMENT',
	COMMENT2 char(31) NOT NULL default '',
	USERDEF1 char(21) NOT NULL default '',
	USERDEF2 char(21) NOT NULL default '',
	CRLMTDLR numeric(19, 5) NOT NULL default 0,
	PYMNTPRI char(3) NOT NULL default '',
	KPCALHST tinyint NOT NULL default 0,
	KGLDSTHS tinyint NOT NULL default 0,
	KPERHIST tinyint NOT NULL default 0,
	KPTRXHST tinyint NOT NULL default 0,
	HOLD tinyint NOT NULL default 0,
	PTCSHACF smallint NOT NULL default 0,
	CREDTLMT smallint NOT NULL default 0,
	WRITEOFF smallint NOT NULL default 0,
	MXWOFAMT numeric(19, 5) NOT NULL default 0,
	SBPPSDED tinyint NOT NULL default 0,
	PPSTAXRT smallint NOT NULL default 0,
	DXVARNUM char(25) NOT NULL default '',
	CRTCOMDT datetime NOT NULL default getdate(),
	CRTEXPDT datetime NOT NULL default getdate(),
	RTOBUTKN tinyint NOT NULL default 0,
	XPDTOBLG tinyint NOT NULL default 0,
	PRSPAYEE tinyint NOT NULL default 0,
	PMAPINDX int NOT NULL default 0,
	PMCSHIDX int NOT NULL default 0,
	PMDAVIDX int NOT NULL default 0,
	PMDTKIDX int NOT NULL default 0,
	PMFINIDX int NOT NULL default 0,
	PMMSCHIX int NOT NULL default 0,
	PMFRTIDX int NOT NULL default 0,
	PMTAXIDX int NOT NULL default 0,
	PMWRTIDX int NOT NULL default 0,
	PMPRCHIX int NOT NULL default 0,
	PMRTNGIX int NOT NULL default 0,
	PMTDSCIX int NOT NULL default 0,
	ACPURIDX int NOT NULL default 0,
	PURPVIDX int NOT NULL default 0,
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	CHEKBKID char(15) NOT NULL default '',
	MODIFDT datetime NOT NULL default getdate(),
	CREATDDT datetime NOT NULL default getdate(),
	RATETPID char(15) NOT NULL default '',
	Revalue_Vendor tinyint NOT NULL default 0,
	Post_Results_To smallint NOT NULL default 0,
	FREEONBOARD smallint NOT NULL default 0,
	GOVCRPID char(31) NOT NULL default '',
	GOVINDID char(31) NOT NULL default '',
	DISGRPER smallint NOT NULL default 0,
	DUEGRPER smallint NOT NULL default 0,
	DOCFMTID char(15) NOT NULL default '',
	TaxInvRecvd tinyint NOT NULL default 0,
	USERLANG smallint NOT NULL default 0,
	WithholdingType smallint NOT NULL default 0,
	WithholdingFormType smallint NOT NULL default 0,
	WithholdingEntityType smallint NOT NULL default 0,
	TaxFileNumMode smallint NOT NULL default 0,
	BRTHDATE datetime NOT NULL default getdate(),
	LaborPmtType smallint NOT NULL default 0,
	CCode char(7) NOT NULL default '',
	DECLID char(15) NOT NULL default '',
	CBVAT tinyint NOT NULL default 0,
	Workflow_Approval_Status smallint NOT NULL default 0,
	Workflow_Priority smallint NOT NULL default 0,
	Workflow_Status smallint NOT NULL default 0,
	VADCD1099 char(15) NOT NULL default '',
	ONEPAYPERVENDINV smallint NOT NULL default 0,
	VENDDBA char(65) NOT NULL default '',
	DEX_ROW_TS datetime NOT NULL default getdate(),
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL)
GO

insert into PM00200 (VENDORID) values ('VEND001')
GO

-- Cash Receipts

CREATE TABLE CR10101 (
	dDOCKEY smallint NOT NULL default 0,
	dDOCSUFFIX numeric(19, 5) NOT NULL primary key,
	BACHNUMB char(15) NOT NULL default 'BATCH001',
	BCHSOURC char(15) NOT NULL default '',
	dINITIALS char(3) NOT NULL default 'XX',
	dSEQNMBR int NOT NULL default 0,
	dLINESEQRM int NOT NULL default 0,
	dDATE datetime NOT NULL default getdate(),
	dDESC char(31) NOT NULL default 'TEST DESCRIPTION',
	dDESC2 char(31) NOT NULL default '',
	dDESC3 char(31) NOT NULL default '',
	dDESC4 char(31) NOT NULL default '',
	dDESC5 char(51) NOT NULL default '',
	dDESC6 char(31) NOT NULL default '',
	dTOTBAL numeric(19, 5) NOT NULL default 10,
	dTXAMOUNT numeric(19, 5) NOT NULL default 0,
	dCASHAMOUNT numeric(19, 5) NOT NULL default 0,
	dCHEQUEAMOUNT numeric(19, 5) NOT NULL default 10,
	dCHEQUENMBR char(21) NOT NULL default '100',
	dCREDITCARDAMOUNT numeric(19, 5) NOT NULL default 0,
	dCREDITCARDNAME char(31) NOT NULL default '',
	dOTHERAMOUNT numeric(19, 5) NOT NULL default 0,
	dCHEQUEBOOKIDCASH char(15) NOT NULL default '',
	dCHEQUEBOOKIDCHEQUE char(15) NOT NULL default '',
	dCHEQUEBOOKIDOTHER char(15) NOT NULL default '',
	dPRINTED tinyint NOT NULL default 0,
	dCRERRORMSG1 binary(4) NOT NULL default 0,
	dPWDPROTECTED tinyint NOT NULL default 0,
	dPAPRCPT tinyint NOT NULL default 0,
	dPAPSERIES smallint NOT NULL default 0,
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	dDATECREATED datetime NOT NULL default getdate(),
	dDATEMODIFIED datetime NOT NULL default getdate(),
	dVOIDED tinyint NOT NULL default 0,
	dPAPFILENMBR char(5) NOT NULL default '',
	dCUSTNMBR char(15) NOT NULL default 'CUST001',
	dADDRCODE char(15) NOT NULL default '',
	dCCPROCOK tinyint NOT NULL default 0,
	dCHARITDONATE tinyint NOT NULL default 0,
	dDTRECIEVED datetime NOT NULL default getdate(),
	dROUNDINGVARIANCE numeric(19, 5) NOT NULL default 0,
	dEMAILBATCHNMBR char(15) NOT NULL default '',
	dEMAILSENT tinyint NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL)
GO

CREATE TABLE CR30101 (
	dTRXSRC char(13) NOT NULL default '',
	dDOCKEY smallint NOT NULL default 0,
	dDOCSUFFIX numeric(19, 5) primary key,
	BACHNUMB char(15) NOT NULL default 'BATCH001',
	BCHSOURC char(15) NOT NULL default '',
	dINITIALS char(3) NOT NULL default 'XX',
	dSEQNMBR int NOT NULL default 0,
	dLINESEQRM int NOT NULL default 0,
	dDATE datetime NOT NULL default getdate(),
	dDESC char(31) NOT NULL default 'TEST DESCRIPTION',
	dDESC2 char(31) NOT NULL default '',
	dDESC3 char(31) NOT NULL default '',
	dDESC4 char(31) NOT NULL default '',
	dDESC5 char(51) NOT NULL default '',
	dDESC6 char(31) NOT NULL default '',
	dTOTBAL numeric(19, 5) NOT NULL default 10,
	dTXAMOUNT numeric(19, 5) NOT NULL default 0,
	dTOTREC numeric(19, 5) NOT NULL default 10,
	dCASHAMOUNT numeric(19, 5) NOT NULL default 0,
	dCHEQUEAMOUNT numeric(19, 5) NOT NULL default 10,
	dCHEQUENMBR char(21) NOT NULL default '100',
	dCREDITCARDAMOUNT numeric(19, 5) NOT NULL default 0,
	dCREDITCARDNAME char(31) NOT NULL default '',
	dOTHERAMOUNT numeric(19, 5) NOT NULL default 0,
	dCHEQUEBOOKIDCASH char(15) NOT NULL default '',
	dCHEQUEBOOKIDCHEQUE char(15) NOT NULL default '',
	dCHEQUEBOOKIDOTHER char(15) NOT NULL default '',
	dPRINTED tinyint NOT NULL default 0,
	NOTEINDX numeric(19, 5) NOT NULL default 0,
	dDATECREATED datetime NOT NULL default getdate(),
	dDATEMODIFIED datetime NOT NULL default getdate(),
	dVOIDED tinyint NOT NULL default 0,
	dPAPFILENMBR char(5) NOT NULL default '',
	dCUSTNMBR char(15) NOT NULL default 'CUST001',
	dADDRCODE char(15) NOT NULL default '',
	dDOCSUFFIXVOIDED numeric(19, 5) NOT NULL default 0,
	dCCPROCOK tinyint NOT NULL default 0,
	dCHARITDONATE tinyint NOT NULL default 0,
	dDTRECIEVED datetime NOT NULL default getdate(),
	dROUNDINGVARIANCE numeric(19, 5) NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL)
GO

insert into CR30101 (dDOCSUFFIX) values (1)
GO

-- Cash Receipt Details

CREATE TABLE CR10102 (
	dDOCSUFFIX numeric(19, 5) NOT NULL,
	dSEQNMBR int NOT NULL,
	dLINESEQRM int NOT NULL default 0,
	dCRRMDOCNMBR char(21) NOT NULL default '',
	dSELECT tinyint NOT NULL default 0,
	dNMBRITEMS smallint NOT NULL default 5,
	dCRTYPE smallint NOT NULL default 0,
	dCRFORMATTYPE smallint NOT NULL default 0,
	dCRACCT char(15) NOT NULL default '',
	dACCTINDEX int NOT NULL default 1,
	dAMOUNTOUTSTANDING numeric(19, 5) NOT NULL default 0,
	dLINEAMOUNT numeric(19, 5) NOT NULL default 10,
	dAMOUNTPAID numeric(19, 5) NOT NULL default 10,
	dUNAPPLIEDAMOUNT numeric(19, 5) NOT NULL default 0,
	dDISCCD char(5) NOT NULL default '',
	dDISCAMOUNT numeric(19, 5) NOT NULL default 0,
	dTXSCHDID char(15) NOT NULL default '',
	dTXAMOUNT numeric(19, 5) NOT NULL default 0,
	dPOSTAMOUNT numeric(19, 5) NOT NULL default 10,
	dCRDTLDESC char(41) NOT NULL default '',
	dCRDTLERRORMSG1 binary(4) NOT NULL default 0,
	dARREARSAMOUNT numeric(19, 5) NOT NULL default 0,
	dDELINQAMOUNT numeric(19, 5) NOT NULL default 0,
	dARREARSINTAMOUNT numeric(19, 5) NOT NULL default 0,
	dDELINQINTAMOUNT numeric(19, 5) NOT NULL default 0,
	dACCTINCOLL tinyint NOT NULL default 0,
	dAUTHNMBR char(51) NOT NULL default '',
	dAUTHMESS char(31) NOT NULL default '',
	dTXNOTFILEDATE datetime NOT NULL default getdate(),
	dSUBSERIES char(5) NOT NULL default '',
	dYEAR smallint NOT NULL default 0,
	dDOGFEECD char(5) NOT NULL default '',
	dRNWLDTE datetime NOT NULL default getdate(),
	dDOGTAG char(13) NOT NULL default '',
	dCRDTLERRORMSG2 binary(4) NOT NULL default 0,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
 CONSTRAINT PKCR10102 PRIMARY KEY CLUSTERED 
(
	dDOCSUFFIX ASC,
	dSEQNMBR ASC
))
GO

CREATE TABLE CR30102 (
	dDOCSUFFIX numeric(19, 5) NOT NULL,
	dSEQNMBR int NOT NULL,
	dLINESEQRM int NOT NULL default 0,
	dCRRMDOCNMBR char(21) NOT NULL default '',
	dSELECT tinyint NOT NULL default 0,
	dNMBRITEMS smallint NOT NULL default 5,
	dCRTYPE smallint NOT NULL default 0,
	dCRFORMATTYPE smallint NOT NULL default 0,
	dCRACCT char(15) NOT NULL default '',
	dACCTINDEX int NOT NULL default 1,
	dAMOUNTOUTSTANDING numeric(19, 5) NOT NULL default 0,
	dLINEAMOUNT numeric(19, 5) NOT NULL default 10,
	dAMOUNTPAID numeric(19, 5) NOT NULL default 10,
	dUNAPPLIEDAMOUNT numeric(19, 5) NOT NULL default 0,
	dDISCCD char(5) NOT NULL default '',
	dDISCAMOUNT numeric(19, 5) NOT NULL default 0,
	dTXSCHDID char(15) NOT NULL default '',
	dTXAMOUNT numeric(19, 5) NOT NULL default 0,
	dPOSTAMOUNT numeric(19, 5) NOT NULL default 10,
	dCRDTLDESC char(41) NOT NULL default '',
	dARREARSAMOUNT numeric(19, 5) NOT NULL default 0,
	dDELINQAMOUNT numeric(19, 5) NOT NULL default 0,
	dARREARSINTAMOUNT numeric(19, 5) NOT NULL default 0,
	dDELINQINTAMOUNT numeric(19, 5) NOT NULL default 0,
	dAUTHNMBR char(51) NOT NULL default '',
	dTXNOTFILEDATE datetime NOT NULL default getdate(),
	dSUBSERIES char(5) NOT NULL default '',
	dYEAR smallint NOT NULL default 0,
	dDOGFEECD char(5) NOT NULL default '',
	dRNWLDTE datetime NOT NULL default getdate(),
	dDOGTAG char(13) NOT NULL default '',
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
 CONSTRAINT PKCR30102 PRIMARY KEY CLUSTERED 
(
	dDOCSUFFIX ASC,
	dSEQNMBR ASC
))
GO

insert into CR30102 (dDOCSUFFIX, dSEQNMBR) values (1, 1)
GO

-- Cash Receipt Distributions

CREATE TABLE CR30103 (
	dDOCSUFFIX numeric(19, 5) NOT NULL,
	dACCTINDEX int NOT NULL,
	dQUICKCD char(5) NOT NULL default '',
	dTXDTLID char(15) NOT NULL default '',
	dAMOUNTPAID numeric(19, 5) NOT NULL default 10,
	DEX_ROW_ID int IDENTITY(1,1) NOT NULL,
 CONSTRAINT PKCR30103 PRIMARY KEY CLUSTERED (dDOCSUFFIX, dACCTINDEX,	dQUICKCD, dTXDTLID))
GO

insert into CR30103 (dDOCSUFFIX, dACCTINDEX) values (1, 1)